### PR TITLE
Remove fortran dependency

### PR DESCRIPTION
**Pull request by devsprint**
- removed fortran dependency and use the C++ wrapper instead.
- updated dependencies
- formatted code

### CODE REVIEW

**Comment by devsprint** [comment]
@krfricke @frnsys  can you guys take a look over this change?

**Review by krfricke — COMMENTED** [review]
Looks good, thanks! Can we split up the PR into one that does the code formatting updates and one that does the lbfgs update? That will make it a bit nicer in the commit history (we'll squash and merge the commits).

**Comment by devsprint** [comment]
@krfricke I'm closing this PR in favor of #5 . Should I do the formatting or you want to keep the current one?

**Comment by krfricke** [comment]
Happy either way. I think the original formatting is a couple of years old now, so if it's just running `cargo fmt`, let's do it and get the new style in

**Pull request closed without merging**
